### ISSUE TITLE
Question regarding function receptor in 'AutoDock.py'

### ISSUE THREAD

**Issue by akshat998** [sarisabban/Notes#1]
Hello, 
I really enjoyed the amazing explanation on the use of AutoDock vina :) 

Since, I have begun incorporating this guide into my own project. I had a question regarding the receptor function & the generated output 'receptor.pdbqt'. I followed the following steps: 

1. grep ATOM protein.pdb > R.pdb
2. python AutoDock.py -r R.pdb

In step 1, there are no water molecules that are generated inside R.pdb. 
However, when I run step 2, the generated receptor.pdbq has the following lines: 
           ATOM      1  O   HOH    1       93.344  30.073  43.622  0.00  0.00    +0.000 OA

Is this to be expected? 
Any advice would be greatly appreciated :) 
Regards, 
Akshat

**Comment by sarisabban** [comment]
When you perform grep ATOM you will be transferring this ATOM 1 O HOH to the new file since this line  contains the string "ATOM", thus it is carried over to R.pdb and thus to receptor.pdbqt

My advice is to not use grep here and just do it manually, simply open the protein.pdb file in a plain text editor (not word or office) and remove everything except the atoms you need. Pay attention here! because sometimes ATOM will include HOH (water) and these should be removed, HETATM of none amino acids should also be removed (like ligands or sugars or DNA), but the HETATM of amino acids like MSE for example should be kept! save your new file as R.pdb and then continue normally.

So make sure you know and understand the structure of your protein before and after the changes you are making.
